//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDhrService.DataStores {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDhrService.DataStores.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM (SELECT 1 As Id, &quot;--Select Table--&quot; AS TableName FROM MSysObjects
        ///UNION
        ///SELECT 2 AS Id, MSysObjects.name AS TableName
        ///FROM MSysObjects
        ///WHERE
        ///MSysObjects.type In (1,4,6)
        ///AND MSysObjects.name not like &apos;~*&apos;   
        ///AND MSysObjects.name not like &apos;MSys*&apos;)
        ///ORDER BY Id.
        /// </summary>
        internal static string MS_SQL_GET_ALL_TABLES {
            get {
                return ResourceManager.GetString("MS_SQL_GET_ALL_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [VISTA_VIEW, Burn-in]([DUT Serial Number], [DUT Location], [Load Operator], [UnLoad Operator], [Date/Time In], [Date/Time Out], [Burn-In Elapsed Time], [Pass/Fail], [Comment])
        ///VALUES(@DustSn, @Location, @LoadOperator, @UnLoadOperator, @DateTimeIn, @DateTimeOut, @ElapsedTime, @PassFail, @Comment).
        /// </summary>
        internal static string MS_SQL_SAVE_VISTA_VIEW_BURN_IN {
            get {
                return ResourceManager.GetString("MS_SQL_SAVE_VISTA_VIEW_BURN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM &quot;StationDetails&quot; WHERE &quot;SpecificationKeyId&quot; = @SpecificationKeyId;.
        /// </summary>
        internal static string SQL_DELETE_STATION_DETAILS {
            get {
                return ResourceManager.GetString("SQL_DELETE_STATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;Save_DataImportExportDtls&quot;(@ImportExportId, @DataImportExportDetails);.
        /// </summary>
        internal static string SQL_FUNC_SAVE_DATA_IMPORT_EXPORT_DTLS {
            get {
                return ResourceManager.GetString("SQL_FUNC_SAVE_DATA_IMPORT_EXPORT_DTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;Id&quot;, &quot;Key&quot;, &quot;IsRequired&quot; FROM &quot;SpecificationKeys&quot; WHERE &quot;Key&quot; = @Key;.
        /// </summary>
        internal static string SQL_GET_SPECIFICATION_BY_NAME {
            get {
                return ResourceManager.GetString("SQL_GET_SPECIFICATION_BY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sk.&quot;Key&quot;, sd.&quot;Value&quot; 
        ///FROM &quot;StationDetails&quot; AS sd 
        ///INNER JOIN &quot;SpecificationKeys&quot; AS sk 
        ///ON sd.&quot;SpecificationKeyId&quot; = sk.&quot;Id&quot;
        ///ORDER BY sk.&quot;Sequence&quot;.
        /// </summary>
        internal static string SQL_GET_STATION_SPECIFIC_FIELDS {
            get {
                return ResourceManager.GetString("SQL_GET_STATION_SPECIFIC_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;StationDetails&quot;(&quot;SpecificationKeyId&quot;, &quot;Value&quot;)
        ///VALUES (@SpecificationKeyId, @SpecificationValue);.
        /// </summary>
        internal static string SQL_SAVE_STATION_DETAILS {
            get {
                return ResourceManager.GetString("SQL_SAVE_STATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = &apos;{0}&apos;.
        /// </summary>
        internal static string SQL_SCHEMA_EXISTS {
            get {
                return ResourceManager.GetString("SQL_SCHEMA_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;Notification&quot;
        ///SET &quot;Attribute&quot; = @Attributes, 
        ///&quot;CreationTime&quot; = @CreationTime, 
        ///&quot;FileName&quot; = @FileName, 
        ///&quot;LastWrite&quot; = @LastWrite, 
        ///&quot;Size&quot; = @Size, 
        ///&quot;IncludeSubFolders&quot; = @IncludeSubFolders.
        /// </summary>
        internal static string SQl_UPDATE_NOTIFICATION {
            get {
                return ResourceManager.GetString("SQl_UPDATE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;StationDetails&quot;
        ///SET &quot;Value&quot; = @SpecificationValue
        ///WHERE &quot;SpecificationKeyId&quot; = @SpecificationKeyId.
        /// </summary>
        internal static string SQL_UPDATE_STATION_DETAILS {
            get {
                return ResourceManager.GetString("SQL_UPDATE_STATION_DETAILS", resourceCulture);
            }
        }
    }
}
